USE tabledb;
CREATE TABLE tbl1
( a INT PRIMARY KEY,
  b INT,
  c INT,
);

USE tabledb;
CREATE TABLE tbl1
( a INT PRIMARY KEY,
  b INT UNIQUE,
  c INT UNIQUE,
  d INT
);

CREATE TABLE tbl5
( a INT UNIQUE NOT NULL,
  b INT UNIQUE,
  c INT UNIQUE,
  d INT PRIMARY KEY
);

USE tabledb;
CREATE TABLE test12
( name1 CHAR(8),
  age INT
);

INSERT INTO test12 VALUES ('ABC', 17);
INSERT INTO test12 VALUES ('DBC', 19);
INSERT INTO test12 VALUES ('UYJ', 31);
INSERT INTO test12 VALUES ('POI', 20);
INSERT INTO test12 VALUES ('ABB', 3);
INSERT INTO test12 VALUES ('NMJ', 23);
INSERT INTO test12 VALUES ('QWE', 27);
INSERT INTO test12 VALUES ('JKL', 22);
INSERT INTO test12 VALUES ('SDF', 12);
INSERT INTO test12 VALUES ('XCV', 8);

ALTER TABLE test12
ADD CONSTRAINT PK_test12_name1
PRIMARY KEY (name1);

